packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: false

catalog:
  '@types/node': 26.5.1
  '@typescript/native': npm:typescript@7.0.2
  '@vitest/coverage-v8': 5.0.1
  jiti: 2.7.0
  jsdom: 30.0.1
  solid-devtools: 0.34.5
  turbo: 2.10.12
  typescript: npm:@typescript/typescript6@6.0.2
  vite: 8.3.0
  vite-plugin-solid: 2.11.14
  vitest: 5.0.1

minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@5.0.1'
  - '@vitest/mocker@5.0.1'
  - '@vitest/spy@5.0.1'
  - vitest@5.0.1
